export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  CREATE_CUSTOMER: "/customers/create",
  GEARS: "/gears",
  GOALS: "/goals",
  CREATE_GEAR: "/gears/create",
  FILIALS: "/filials",
  CREATE_FILIAL: "/filials/create",
  EMPLOYEES: "/employees",
  CREATE_EMPLOYEE: "/employees/create",
  CALENDAR: "/calendar",
  CREATE_BOOKING: "/bookings/create",
  BOOKING_TABLE: "/bookings",
  CITY_DISTANCES: "/city-distances",
  ROUTES: "/routes",
  // VIEW_CALENDAR: "/bookings",
  TRAININGS: "/trainings",
  BIRTHDAYS: "/birthdays",
  NOTICES: "/notices",
};
